#!/usr/bin/env python
"""Emit se_test_feats.h — a few baked 3-channel feature frames for on-board bring-up.

Mirrors the N6 firmware_router's ``router_feats.h``: a small fixed input sequence so
the board can run the streaming loop and report latency/output without needing live
audio + a codec yet. Values are a deterministic pattern (bring-up is about "does it
run + how fast", not enhancement quality — that needs the trained model + real audio).
"""
import argparse
import math
from pathlib import Path


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--frames", type=int, default=16)
    ap.add_argument("--n_freqs", type=int, default=257)
    ap.add_argument("--output", default="deploy/rt595/app/se_test_feats.h")
    a = ap.parse_args()

    out = Path(a.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    F, T = a.n_freqs, a.frames

    L = ["/* AUTO-GENERATED by deploy/rt595/host/gen_test_feats.py — DO NOT EDIT. */",
         "/* Deterministic bring-up feature frames: [T][3][F], channel-major per frame. */",
         "#ifndef SE_TEST_FEATS_H", "#define SE_TEST_FEATS_H", "",
         f"#define SE_TEST_FRAMES  ({T})",
         f"#define SE_TEST_N_FREQS ({F})",
         "static const float se_test_feats[SE_TEST_FRAMES][3 * SE_TEST_N_FREQS] = {"]
    for t in range(T):
        vals = []
        for c in range(3):
            for f in range(F):
                # smooth, bounded pattern varying over time/freq/channel
                v = 0.5 * math.sin(0.03 * f + 0.2 * t + c) * math.exp(-f / (2.0 * F))
                vals.append(v)
        body = ", ".join(f"{v:.6f}f" for v in vals)
        L.append(f"  {{ {body} }},")
    L += ["};", "", "#endif /* SE_TEST_FEATS_H */"]
    out.write_text("\n".join(L) + "\n")
    print(f"Wrote {out}  ({T} frames x {3*F} floats)")


if __name__ == "__main__":
    main()
