#!/usr/bin/env python
"""Emit se_test_feats.h with a configurable channel count (multi-model companion).

gen_test_feats.py bakes 3-channel LiSenNet frames; convfsenet/nsnet2 feed a single
channel. --channels sets the per-frame width (channels * n_freqs). Deterministic
bring-up pattern — this measures "does it run + how fast", not enhancement quality.
"""
import argparse
import math
from pathlib import Path


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--frames", type=int, default=16)
    ap.add_argument("--n_freqs", type=int, default=257)
    ap.add_argument("--channels", type=int, default=1)
    ap.add_argument("--output", required=True)
    a = ap.parse_args()

    out = Path(a.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    F, T, C = a.n_freqs, a.frames, a.channels

    L = ["/* AUTO-GENERATED by deploy/rt595/host/gen_test_feats_multi.py — DO NOT EDIT. */",
         f"/* Deterministic bring-up frames: [T][{C}*F], channel-major per frame. */",
         "#ifndef SE_TEST_FEATS_H", "#define SE_TEST_FEATS_H", "",
         f"#define SE_TEST_FRAMES  ({T})",
         f"#define SE_TEST_N_FREQS ({F})",
         f"#define SE_TEST_CHANNELS ({C})",
         f"static const float se_test_feats[SE_TEST_FRAMES][{C} * SE_TEST_N_FREQS] = {{"]
    for t in range(T):
        vals = []
        for c in range(C):
            for f in range(F):
                v = 0.5 * math.sin(0.03 * f + 0.2 * t + c) * math.exp(-f / (2.0 * F))
                vals.append(v)
        body = ", ".join(f"{v:.6f}f" for v in vals)
        L.append(f"  {{ {body} }},")
    L += ["};", "", "#endif /* SE_TEST_FEATS_H */"]
    out.write_text("\n".join(L) + "\n")
    print(f"Wrote {out}  ({T} frames x {C*F} floats)")


if __name__ == "__main__":
    main()
