#!/usr/bin/env python
"""Emit model_data.h — the .tflite flatbuffer as a C array for the M33 firmware.

Mirrors how the mcuxsdk eiq examples embed their model (``cpu/model_data.h``): a
16-byte-aligned ``const uint8_t model_data[]`` plus ``model_data_len``, so TFLM's
``tflite::GetModel(model_data)`` can map it in place from flash.
"""
import argparse
from pathlib import Path


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", required=True, help="the .tflite to embed")
    ap.add_argument("--output", default=None, help="model_data.h path")
    ap.add_argument("--name", default="model_data", help="C array symbol name")
    a = ap.parse_args()

    blob = Path(a.model).read_bytes()
    out_path = Path(a.output) if a.output else Path(a.model).with_name("model_data.h")
    out_path.parent.mkdir(parents=True, exist_ok=True)

    lines = ["/* AUTO-GENERATED by deploy/rt595/host/gen_model_data.py — DO NOT EDIT. */",
             f"/* source: {Path(a.model).resolve()} ({len(blob)} bytes) */",
             "#ifndef MODEL_DATA_H", "#define MODEL_DATA_H", "",
             "#include <stdint.h>", "",
             f"#define {a.name}_len ({len(blob)})",
             f"__attribute__((aligned(16))) const unsigned char {a.name}[] = {{"]
    for i in range(0, len(blob), 12):
        chunk = blob[i:i + 12]
        lines.append("  " + "".join(f"0x{b:02x}, " for b in chunk).rstrip())
    lines += ["};", "", "#endif /* MODEL_DATA_H */"]
    out_path.write_text("\n".join(lines) + "\n")
    print(f"Wrote {out_path}  ({len(blob)} bytes -> {out_path.stat().st_size/1024:.1f} KiB C array)")


if __name__ == "__main__":
    main()
