/* AUTO-GENERATED by deploy/rt595/host/gen_io_layout.py — DO NOT EDIT. */
/* source: /home/claroche/eco8-neaixt/deploy/rt595/host_out/lisennet_conv_hardened_streaming_fp32.tflite */
#ifndef MODEL_IO_LAYOUT_H
#define MODEL_IO_LAYOUT_H

#define MODEL_N_IO            (18)   /* inputs == outputs */
#define MODEL_N_STATES        (17)

/* feat: interpreter->input(MODEL_FEATURE_IN_POS); est_mag: ->output(MODEL_MASK_OUT_POS). */
#define MODEL_FEATURE_IN_POS  (5)
#define MODEL_FEATURE_LEN     (257)   /* freq bins */
#define MODEL_FEATURE_IS_INT8 (0)
#define MODEL_MASK_OUT_POS    (10)
#define MODEL_MASK_LEN        (257)

/* On-device quant: q = round(x/scale)+zp; dequant: x = (q-zp)*scale. */
#define MODEL_FEATURE_SCALE   (0.0f)
#define MODEL_FEATURE_ZEROPOINT (0)
#define MODEL_MASK_SCALE      (0.0f)
#define MODEL_MASK_ZEROPOINT  (0)

/* 1 = every state_in[k]/state_out[k] shares scale+zp -> feedback is a raw memcpy. */
#define MODEL_STATE_FEEDBACK_MEMCPY_SAFE (1)

/* Per-state feedback map. Each frame the driver copies output(out_pos) into
   input(in_pos): raw memcpy if memcpy_safe, else dequant(out)*->requant(in). */
typedef struct {
  int   in_pos, out_pos;   /* interpreter->input(in_pos) / ->output(out_pos) */
  int   count;             /* element count (int8: == byte size)             */
  float in_scale;  int in_zp;
  float out_scale; int out_zp;
  int   memcpy_safe;
} model_state_map_t;
static const model_state_map_t MODEL_STATE_MAP[MODEL_N_STATES] = {
  { 15,  2,   1536, 0.0f,    0, 0.0f,    0, 1 },  /* state  0 float32 */
  {  2, 11,   4632, 0.0f,    0, 0.0f,    0, 1 },  /* state  1 float32 */
  {  3,  7,   1536, 0.0f,    0, 0.0f,    0, 1 },  /* state  2 float32 */
  { 11,  1,   4608, 0.0f,    0, 0.0f,    0, 1 },  /* state  3 float32 */
  {  0,  6,   1152, 0.0f,    0, 0.0f,    0, 1 },  /* state  4 float32 */
  { 10, 17,   3456, 0.0f,    0, 0.0f,    0, 1 },  /* state  5 float32 */
  { 17,  3,   6144, 0.0f,    0, 0.0f,    0, 1 },  /* state  6 float32 */
  { 13, 13,  12288, 0.0f,    0, 0.0f,    0, 1 },  /* state  7 float32 */
  {  4,  0,  24576, 0.0f,    0, 0.0f,    0, 1 },  /* state  8 float32 */
  {  7, 15,  49152, 0.0f,    0, 0.0f,    0, 1 },  /* state  9 float32 */
  {  9, 14,  12288, 0.0f,    0, 0.0f,    0, 1 },  /* state 10 float32 */
  {  1,  5,   6144, 0.0f,    0, 0.0f,    0, 1 },  /* state 11 float32 */
  { 12,  8,  12288, 0.0f,    0, 0.0f,    0, 1 },  /* state 12 float32 */
  {  6,  4,  24576, 0.0f,    0, 0.0f,    0, 1 },  /* state 13 float32 */
  { 14, 12,  49152, 0.0f,    0, 0.0f,    0, 1 },  /* state 14 float32 */
  {  8, 16,  12288, 0.0f,    0, 0.0f,    0, 1 },  /* state 15 float32 */
  { 16,  9,   6144, 0.0f,    0, 0.0f,    0, 1 },  /* state 16 float32 */
};

#endif /* MODEL_IO_LAYOUT_H */
