/* AUTO-GENERATED by deploy/rt595/host/gen_io_layout_multi.py — DO NOT EDIT. */
/* model: nsnet2   source: deploy/rt595/host_out/nsnet2_blockdiagfull_streaming.tflite */
#ifndef MODEL_IO_LAYOUT_H
#define MODEL_IO_LAYOUT_H

#define MODEL_NAME            "nsnet2"
#define MODEL_N_IO            (2)   /* inputs == outputs */
#define MODEL_N_STATES        (1)

#define MODEL_FEATURE_IN_POS  (0)
#define MODEL_FEATURE_LEN     (257)   /* last dim (freq bins) */
#define MODEL_FEATURE_TOTAL   (257)   /* product of all feat dims */
#define MODEL_FEATURE_IS_INT8 (1)
#define MODEL_MASK_OUT_POS    (1)
#define MODEL_MASK_LEN        (257)

#define MODEL_FEATURE_SCALE   (0.016947323456406593f)
#define MODEL_FEATURE_ZEROPOINT (-128)
#define MODEL_MASK_SCALE      (0.00390625f)
#define MODEL_MASK_ZEROPOINT  (-128)

#define MODEL_STATE_FEEDBACK_MEMCPY_SAFE (0)

typedef struct {
  int   in_pos, out_pos;
  int   count;
  float in_scale;  int in_zp;
  float out_scale; int out_zp;
  int   memcpy_safe;
} model_state_map_t;
static const model_state_map_t MODEL_STATE_MAP[MODEL_N_STATES] = {
  {  1,  0,    800, 0.007836547680199146f,    0, 0.007843133062124252f,    0, 0 },  /* state  0 int8 */
};

#endif /* MODEL_IO_LAYOUT_H */
