/* AUTO-GENERATED by deploy/stm32n6/host/gen_io_layout.py — DO NOT EDIT. */
/* source: /home/claroche/eco8-neaixt/deploy/stm32n6/st_ai_output/g_best_OE_3_3_1.onnx */
#ifndef MODEL_IO_LAYOUT_H
#define MODEL_IO_LAYOUT_H

#define MODEL_N_IO            (10)   /* inputs == outputs */
#define MODEL_N_STATES        (9)

/* Input 0 is the float32 magnitude feature; inputs 1..N are int8 recurrent state. */
#define MODEL_FEATURE_IN_IDX  (0)
#define MODEL_FEATURE_LEN     (257)   /* freq bins; float32 */
#define MODEL_MASK_OUT_IDX    (0)
#define MODEL_MASK_LEN        (257)   /* int8 */

/* Mask dequant: mask_f = (q - zp) * scale, q in [-128,127]. */
#define MODEL_MASK_SCALE      (0.003921568859368563f)
#define MODEL_MASK_ZEROPOINT  (-128)

/* int8 code for float 0.0 at the state boundary (zp == -128 here): zero-init value. */
#define MODEL_STATE_ZERO_CODE ((int8_t)(-128))

/* Verified: state_out[k] and state_in[k] share scale+zp, so feedback = raw memcpy.
   STATE_FEED maps the 0-based feedback pairs onto the I/O arrays (in/out idx == k). */
#define MODEL_STATE_FIRST_IDX (1)   /* states occupy I/O indices 1..MODEL_N_STATES */

/* Verify against the generated stai_network.h at compile time. */
#ifdef STAI_NETWORK_IN_NUM
_Static_assert(STAI_NETWORK_IN_NUM == MODEL_N_IO,  "IN count drift vs model_io_layout.h");
_Static_assert(STAI_NETWORK_OUT_NUM == MODEL_N_IO, "OUT count drift vs model_io_layout.h");
#endif

#endif /* MODEL_IO_LAYOUT_H */
