#!/usr/bin/env python3
"""Emit app/model_io_layout.h from a stedgeai-compiled *_OE_*.onnx model.

The DPU glue (ai_dpu_se_stream.c) needs to know, for the compiled model:
  - which input is the float32 feature (noisy_mag) vs the int8 recurrent states,
  - the int8 dequant params for the mask output,
  - and the output->input state-feedback map, with a guarantee that each fed-back
    state pair shares identical int8 scale+zero-point (so feedback is a raw memcpy).

This reads the COMPILED graph (the one stedgeai emits next to network.c, named
*_OE_<v>.onnx), where the QDQ boundary has been folded: state/ mask boundaries are
int8 with a single QuantizeLinear (output) / DequantizeLinear (input) carrying the
scale+zero-point. Re-run after every `make generate`; it hard-fails if the memcpy
assumption (scale_in[k] == scale_out[k]) ever breaks for a future model.

Usage: gen_io_layout.py <model_OE.onnx> <out_header.h>
Assumes the ConvFSENet streaming I/O convention:
  inputs  = [noisy_mag(float32), state_0_in(int8), ... state_8_in(int8)]
  outputs = [mask(int8),         state_0_out(int8), ... state_8_out(int8)]
"""
import sys, math
import onnx
from onnx import numpy_helper

REL_TOL = 1e-4  # float32-repr tolerance for "same scale"


def main(model_path: str, out_path: str) -> int:
    m = onnx.load(model_path)
    g = m.graph
    init = {i.name: numpy_helper.to_array(i) for i in g.initializer}
    prod = {o: n for n in g.node for o in n.output}
    cons: dict[str, list] = {}
    for n in g.node:
        for i in n.input:
            cons.setdefault(i, []).append(n)

    def scalar(name):
        a = init.get(name)
        if a is None:
            return None
        return float(a) if a.ndim == 0 else float(a.reshape(-1)[0])

    def in_qparams(io):  # input boundary: DequantizeLinear consuming it
        for n in cons.get(io, []):
            if n.op_type == "DequantizeLinear":
                return scalar(n.input[1]), (int(scalar(n.input[2])) if len(n.input) > 2 else 0)
        return None, None  # float input (no boundary DQ)

    def out_qparams(io):  # output boundary: QuantizeLinear producing it
        p = prod.get(io)
        if p is not None and p.op_type == "QuantizeLinear":
            return scalar(p.input[1]), (int(scalar(p.input[2])) if len(p.input) > 2 else 0)
        return None, None

    gi = [t.name for t in g.input]
    go = [t.name for t in g.output]
    n_in, n_out = len(gi), len(go)
    n_states = n_in - 1
    assert n_out == n_in, f"expected equal in/out count, got {n_in}/{n_out}"

    # input 0 = float feature (noisy_mag); outputs 1..n = state feedback into inputs 1..n.
    feat_scale, _ = in_qparams(gi[0])
    if feat_scale is not None:
        print(f"WARNING: input[0] ({gi[0]}) looks quantized (scale={feat_scale}); "
              f"expected a float32 feature input.", file=sys.stderr)
    mask_scale, mask_zp = out_qparams(go[0])
    assert mask_scale is not None, f"output[0] ({go[0]}) has no QuantizeLinear boundary"

    # Verify the memcpy assumption for every fed-back state pair.
    mismatches = []
    for k in range(1, n_in):
        si, zi = in_qparams(gi[k])
        so, zo = out_qparams(go[k])
        if si is None or so is None:
            mismatches.append((k, f"missing qparams in={si} out={so}"))
        elif zi != zo or not math.isclose(si, so, rel_tol=REL_TOL):
            mismatches.append((k, f"scale/zp differ: in=({si},{zi}) out=({so},{zo})"))
    if mismatches:
        print("ERROR: state feedback is NOT a safe raw memcpy for these pairs:", file=sys.stderr)
        for k, why in mismatches:
            print(f"  state pair {k-1}: {why}", file=sys.stderr)
        print("  -> the glue's memcpy fast-path is invalid; you must dequant->requant "
              "per frame using per-state scales. Aborting header generation.", file=sys.stderr)
        return 2

    guard = "MODEL_IO_LAYOUT_H"
    L = []
    L.append("/* AUTO-GENERATED by deploy/stm32n6/host/gen_io_layout.py — DO NOT EDIT. */")
    L.append(f"/* source: {model_path} */")
    L.append(f"#ifndef {guard}\n#define {guard}\n")
    L.append(f"#define MODEL_N_IO            ({n_in})   /* inputs == outputs */")
    L.append(f"#define MODEL_N_STATES        ({n_states})\n")
    L.append("/* Input 0 is the float32 magnitude feature; inputs 1..N are int8 recurrent state. */")
    L.append("#define MODEL_FEATURE_IN_IDX  (0)")
    L.append("#define MODEL_FEATURE_LEN     (257)   /* freq bins; float32 */")
    L.append("#define MODEL_MASK_OUT_IDX    (0)")
    L.append("#define MODEL_MASK_LEN        (257)   /* int8 */\n")
    L.append("/* Mask dequant: mask_f = (q - zp) * scale, q in [-128,127]. */")
    L.append(f"#define MODEL_MASK_SCALE      ({mask_scale!r}f)")
    L.append(f"#define MODEL_MASK_ZEROPOINT  ({mask_zp})\n")
    L.append("/* int8 code for float 0.0 at the state boundary (zp == -128 here): zero-init value. */")
    L.append("#define MODEL_STATE_ZERO_CODE ((int8_t)(-128))\n")
    L.append("/* Verified: state_out[k] and state_in[k] share scale+zp, so feedback = raw memcpy.")
    L.append("   STATE_FEED maps the 0-based feedback pairs onto the I/O arrays (in/out idx == k). */")
    L.append("#define MODEL_STATE_FIRST_IDX (1)   /* states occupy I/O indices 1..MODEL_N_STATES */")
    L.append("")
    L.append("/* Verify against the generated stai_network.h at compile time. */")
    L.append("#ifdef STAI_NETWORK_IN_NUM")
    L.append("_Static_assert(STAI_NETWORK_IN_NUM == MODEL_N_IO,  \"IN count drift vs model_io_layout.h\");")
    L.append("_Static_assert(STAI_NETWORK_OUT_NUM == MODEL_N_IO, \"OUT count drift vs model_io_layout.h\");")
    L.append("#endif\n")
    L.append(f"#endif /* {guard} */")

    with open(out_path, "w") as f:
        f.write("\n".join(L) + "\n")
    print(f"[gen_io_layout] wrote {out_path}: {n_in} I/O, {n_states} states, "
          f"mask scale={mask_scale:.6g} zp={mask_zp}; state feedback memcpy-safe ✓")
    return 0


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(__doc__)
        sys.exit(1)
    sys.exit(main(sys.argv[1], sys.argv[2]))
